name: app-equip-scan
version: '3.8'

services:
  app-equip-scan:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://10.130.12.13:82
        - https_proxy=http://10.130.12.13:82
    container_name: equip-scan
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      # Mapeia a pasta local de credenciais para dentro do container
      ##- /credenciais:/credenciais
      - .:/app
      - /automacao/config:/secrets:ro
    env_file:
      - ./secrets/.env
    environment:
      # Caminho da credencial conforme configurado na aplicação
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/vtal-inventariorede-prd.json
      - FLASK_ENV=production
      # PROXY
      - http_proxy=http://10.130.12.13:82
      - https_proxy=http://10.130.12.13:82
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8081"]


