name: app-equip-scan

services:
  app-equip-scan:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://10.130.12.13:82
        - https_proxy=http://10.130.12.13:82
    container_name: equip-scan
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /automacao/config:/secrets:ro
    env_file:
      - ./secrets/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/vtal-inventariorede-prd.json
      - http_proxy=http://10.130.12.13:82
      - https_proxy=http://10.130.12.13:82
      - BUCKET_NAME=vtal-bucket-inventariorede-prd
      - BUCKET_PATH=fotos_bot_telegram
    # Executamos python app.py diretamente para usar o uvicorn interno do seu script
    command: ["python", "app.py"]